# **Библиотека NumPy**
Эта библиотека используется для работы с многомерными массивами.

Начнем с того, что установим NumPy.

In [ ]:
!pip install numpy

Теперь подключим ее и начнем разбираться с основными возможностями.

In [ ]:
import numpy as np

Главным объектом numpy является многомерный массив np.ndarray, он намного быстрее обычного list.

# Создание массивов

In [ ]:
a1 = np.array([1, 2, 3]) # одномерный массив

a2 = np.array([[1, 2, 3],
             [4, 5, 6]]) # двумерный массив

a3 = np.array([[[1, 2], [3, 4]],
              [[5, 6], [7, 8]]]) # трёхмерный массив

# по такой схеме можно создать сколь угодно многомерный массив

In [ ]:
np.array([1, 2, 3], dtype=float) # можем задавать тип элементов, по умолчанию стоит int32

array([1., 2., 3.])

size, shape, ndim - в чем разница?

In [ ]:
print(a3.ndim)  # так можем узнать количество измерений

print(a2.size)  # так получим количество элементов всего
print(a2.shape) # так можем узнать размеры массива в каждом измерении

print(a1.shape) # обратите внимание как выглядит размер вектора

3
6
(2, 3)
(3,)


Изменение размерности через reshape. Обратите внимание, что новая размерность должна соответствовать количеству элементов



In [ ]:
a = np.array([[1, 2, 3],
             [4, 5, 6]])
print(np.reshape(a, (1, 6)))
print(np.reshape(a, (3, 2)))

[[1 2 3 4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


Если нам нужно привести к одномерному массиву, то можно использовать `flatten()` или `ravel()`

In [ ]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [ ]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

В чем их различие? `flatten()` возвращает копию, в то время как `ravel()` создает ссылку, поэтому если в исходном массиве поменяется элемент, то и в `ravel` он изменится



---


Еще немного о создании массивов

In [ ]:
np.zeros((2, 3)) # массив размера 2х3, заполненный нулями

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((3, 2)) # массив размера 3х2, заполненный единицами

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
np.eye(4) # единичная матрица размера 4х4

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.full((3, 2), 4) # матрица размера 3х2, заполненная 4

array([[4, 4],
       [4, 4],
       [4, 4]])

In [ ]:
np.linspace(1, 5, 9) # массив содержащий 9 чисел от 1 до 5 с равными промежутками

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])



---


Если хотим заполнить массив случайными значениями, есть такие варианты:


*   `np.random.rand(n, m)` - массив случайных чисел от 0.0 до 1.0 размера nxm
*   `np.random.random(n)` - массив случайных чисел от 0.0 до 1.0 длины n
*   `np.random.randint(a, b, (m, n))` - массив случайных целых чисел от a до b размера mxn






---
Можно обращаться отдельно к элементам массива, строкам, столбцам, брать
"подмассив"

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(a[0, 0])
print(a[:, 2])
print(a[0, :])
print(a[:2, :2])

1
[3 6 9]
[1 2 3]
[[1 2]
 [4 5]]




---

Если мы хотим скопировать массив, то важно это делать через метод `copy()`, а не равенство, на примере посмотрим, почему именно так

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = a
b[0, 0] = 0
print(a)
print(b)

[[0 2]
 [3 4]]
[[0 2]
 [3 4]]


Как видим, мы изменяли массив b, но a тоже изменился... Поэтому делаем вот так:

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = a.copy()
b[0, 0] = 0
print(a)
print(b)

[[0 2]
 [3 4]]
[[1 2]
 [3 4]]


---
Как соединить два массива в один?

In [ ]:
a = np.ones((2, 2))
b = np.zeros((2, 2))
print(np.concatenate((a, b), axis=0))
print(np.concatenate((a, b), axis=1))

[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]


In [ ]:
a = np.ones((1, 3))
b = np.zeros((2, 3))
np.vstack((a, b)) # вертикальное присоединение, равносильно np.concatenate((a, b), axis=0)

array([[1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
a = np.ones((2, 2))
b = np.zeros((2, 3))
np.hstack((a, b)) # горизонтальное присоединение, равносильно np.concatenate((a, b), axis=1)

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

Обратите внимание, что здесь также важно следить за размерностью



---

Рассмотрим как добавлять что-то в массив

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

np.append(a, b) # как для list

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.insert(a, 1, b, axis=0) # в массив a добавить массив b после 1 строки

array([[1, 2],
       [5, 6],
       [7, 8],
       [3, 4]])

In [ ]:
np.resize(a, (4, 2)) # если новый размер больше, то заполнит копиями массива

array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 4]])

In [ ]:
a.resize((4, 2), refcheck=False) # если новый размер больше, то заполнит нулями
a

array([[1, 2],
       [3, 4],
       [0, 0],
       [0, 0]])

# Операции с матрицами

In [ ]:
a = np.array([[1, 2, 3],
             [4, 5, 6],
              [7, 8, 9]])

In [ ]:
a.T # транспонирование

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.transpose(a) # другой вариант транспонирования

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.diagonal(a) # главная диагональ матрицы

array([1, 5, 9])



---


Математические операции происходят поэлементно как для двух матриц, так и для матрицы и скаляра (матричное умножение рассмотрим
немного позже)

In [ ]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [ ]:
a + b

array([[ 6,  8],
       [10, 12]])

In [ ]:
a - b

array([[-4, -4],
       [-4, -4]])

In [ ]:
a * b

array([[ 5, 12],
       [21, 32]])

In [ ]:
a / b

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [ ]:
a ** 2

array([[ 1,  4],
       [ 9, 16]])

In [ ]:
1 / a

array([[1.        , 0.5       ],
       [0.33333333, 0.25      ]])

In [ ]:
np.sin(a) # также применится ко всем элементам

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [ ]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [ ]:
a < 3 # поэлементно выполнится сравнение

array([[ True,  True],
       [False, False]])

Раз начали про сравнения, посмотрим на то, как можно фильтровать элементы массива

In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
a[(a > 3) & (a <= 8) | (a == 1)]

array([1, 4, 5, 6, 7, 8])

In [ ]:
(a > 0).all() # проверить, все ли значения True

True

In [ ]:
(a > 9).any() # проверить, есть ли хоть одно значение True

False



---

Теперь вернемся к вопросу о матричном умножении

In [ ]:
a = np.array([[1, 2], [3, 4], [5, 6]])
b = np.ones((2, 3))

In [ ]:
np.matmul(a, b)

array([[ 3.,  3.,  3.],
       [ 7.,  7.,  7.],
       [11., 11., 11.]])

In [ ]:
np.matmul(b, a)

array([[ 9., 12.],
       [ 9., 12.]])

Напомню, что в общем случае матричное умножение не мультипликативно и важно следить за соответствием размероностей, чтобы было возможно выполнить операцию

In [ ]:
np.dot(a, b)

array([[ 3.,  3.,  3.],
       [ 7.,  7.,  7.],
       [11., 11., 11.]])

In [ ]:
a.dot(b)

array([[ 3.,  3.,  3.],
       [ 7.,  7.,  7.],
       [11., 11., 11.]])

In [ ]:
a @ b

array([[ 3.,  3.,  3.],
       [ 7.,  7.,  7.],
       [11., 11., 11.]])

Это все были разные варианты записи одного и того же умножения двух матриц

In [ ]:
a = np.array([[1, 2], [3, 4]])
np.prod(a) # произведение всех элементов матрицы

24

In [ ]:
np.sum(a) # сумма всех элементов матрицы

10



---

Еще немного о фильтрации



*   `np.where(cond, act1, act2)` - поэлементно, если `cond=True` выполняется `act1`, иначе `act2`
*   `np.clip(a, a_min, a_max)` - все, что меньше `a_min`, теперь равно `a_min`, все, что больше `a_max`, равно `a_max`



In [ ]:
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
np.where(a >= 5, a * 2, 0)

array([[ 0,  0,  0],
       [ 0, 10, 12],
       [14, 16, 18]])

In [ ]:
np.clip(a, 2, 8)

array([[2, 2, 3],
       [4, 5, 6],
       [7, 8, 8]])

# np.linalg
Это модуль с множеством функций из линейной алгебры

Вот некоторые из них:


*   `np.linalg.det` - определитель матрицы
*   `np.linalg.inv` - обратная матрица (если матрица необратима, то найде псевдообратную)
*   `np.linalg.norm` - матричная норма
*   `np.linalg.svd` - SVD разложение
*   `np.linalg.qr` - QR разложение
*   `np.linalg.solve(a, b)` - решение системы ax=b



---
Это был краткий обзор базовых функций, NumPy дает возможность эффективно анализировать данные, хорошо служит для задач линейной алгебры и статистики.